### PR TITLE
Finish packaging + added hashmaps to get entity attributes from id

### PR DESCRIPTION
**Pull request by mding010705**

### CODE REVIEW

**Review by williamb700 — DISMISSED** [review]
Good packaging, it was as we discussed.

**Review by williamb700 — DISMISSED** [review]
Nice catch with the login logic as well.

**Review by Khazanah-spec — DISMISSED** [review]
Nice packaging, hashmaps greatly increase convenience.

**Review by nikanali — APPROVED** [review]
Nice Work

**Review by williamb700 — APPROVED** [review]
Nice to see the merge conflicts taken care of.

**Pull request merged**
